apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
  - password=redhat
resources:
  - pvc.yml
  - service.yml
  - mysql.yml
  - wordpress.yml