apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    prod: IN
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
    prod: IN
  clusterIP: None